[package]
name = "thwaite"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayref = "0.3.9"
bincode = "1.3.3"
bytes = "1.9.0"
enum-utils = "0.1.2"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["serde_derive"] }
snap = "1.1.1"
